name: Go Tests and Linting

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run unit tests
        run: |
          echo "Looking for homework test directories..."

          # find all directories with 'homework' in the path
          DIRS=$(find . -type d -path '*/homework*')

          if [ -z "$DIRS" ]; then
            echo "⚠️  No homework directories found."
            exit 0
          fi

          EXIT_CODE=0

          for d in $DIRS; do
            # check if the dir even has *_test.go files
            if ls "$d"/*_test.go >/dev/null 2>&1; then
              echo "────────────────────────────────"
              echo "Running tests in: $d"
              (cd "$d" && go test -v .) || EXIT_CODE=$?
            else
              echo "Skipping $d (no tests)"
            fi
          done

          exit $EXIT_CODE
        env:
          GO111MODULE: off

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: sprints/sprint-04-goroutines/homework
          args: --timeout=5m
