name: Go Tests and Linting

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run unit tests
        run: |
          echo "Finding homework test packages..."
          PKGS=$(go list ./... | grep '/homework/' || true)

          if [ -z "$PKGS" ]; then
            echo "⚠️  No homework packages found."
            exit 0
          fi

          echo "Running tests for packages:"
          echo "$PKGS" | sed 's/^/  • /'

          go test -v $PKGS
        env:
          GO111MODULE: off

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: sprints/sprint-04-goroutines/homework
          args: --timeout=5m
